---
name: Create demo repository
description: This issue will trigger an automation to create a demo repository
  in the chosen organization.
title: tmpl-workflows-100 - [Template]
labels: "demo,workflow,template"
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Please, fill in the following fields to get started with your GitHub workflows demo repository!🚀
  - type: input
    id: user
    attributes:
      label: User handle
      description: Who will be the ownr of the repository?
      placeholder: octocat
    validations:
      required: true
  - type: input
    id: organization
    attributes:
      label: Target organization
      description: Where do you want the repository to get deployed to?
      placeholder: myorg
    validations:
      required: true
  - type: dropdown
    id: repository
    attributes:
      label: Demo repository
      description: Please, select the demo repository you want to deploy
      options:
        - tmpl-workflows-100
    validations:
      required: true
