name: Demo Issue Form Opened

on:
  workflow_call:
    inputs:
      organization_name:
        description: The name of the target organization
        type: string
        required: true
      repository_name:
        description: The name of the template repository
        type: string
        required: true
  workflow_dispatch:
    inputs:
      organization_name:
        description: The name of the target organization
        type: string
        required: true
        default: margaritasdr
      repository_name:
        description: The name of the template repository
        type: string
        required: true 
        default: tmpl-workflows-100 

jobs:
  create_demo:
    name: Create Demo Repository and Resources
    runs-on: ubuntu-20.04
    environment:
      name: ${{ inputs.repository_name }}
    steps:

      - name: Get Token for checkout origin organization
        id: get_workflow_token_origin
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APP_ID }}
          application_private_key: ${{ secrets.APP_SECRET }}
          organization: msanzdelrio-demo-resources

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Checkout template Repository
        uses: actions/checkout@v3
        with:
          repository: msanzdelrio-demo-resources/${{ inputs.repository_name }}
          ref: main
          token: ${{ steps.get_workflow_token_origin.outputs.token }}
          persist-credentials: false
          path: template

      - name: Get Token for checkout target organizatiom
        id: get_workflow_token_target
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APP_ID }}
          application_private_key: ${{ secrets.APP_SECRET }}
          organization: ${{ inputs.organization_name }}

      # - name: Create target repository
      #   id: create_repository
      #   uses: actions/github-script@v6
      #   with:
      #     github-token: ${{ steps.get_workflow_token_target.outputs.token }}
      #     script: |
      #       github.rest.repos.createInOrg({
      #         org: '${{ inputs.organization_name }}',
      #         name: '${{ inputs.repository_name }}',
      #       });


      - name: Push repository changes
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token_target.outputs.token }}
        run: |
          cd ./template
          git init 
          git commit -m 'My first commit'
          git remote set-url origin https://${{ secrets.APP_ID }}:${{ env.GITHUB_TOKEN }}github.com/${{ inputs.organization_name }}/${{ inputs.repository_name }}.git
          git push -u origin main