name: Remove demo repository

on:
  workflow_call:
    inputs:
      user_name:
        description: The name of the user who created the repository
        type: string
        required: true
      organization_name:
        description: The name of the target organization
        type: string
        required: true
      repository_name:
        description: The name of the template repository
        type: string
        required: true
    secrets:
      APP_ID:
        description: 'GitHub App ID'
        required: true
      APP_SECRET:
        description: 'GitHub App key'
        required: true
  workflow_dispatch:
    inputs:
      user_name:
        description: The name of the user who created the repository
        type: string
        required: true
        default: msanzdelrio
      organization_name:
        description: The name of the target organization
        type: string
        required: true
        default: margaritasdr
      repository_name:
        description: The name of the template repository
        type: string
        required: true 
        default: tmpl-workflows-100 

jobs:
  remove_demo:
    name: Remove Demo Repository and Resources
    runs-on: ubuntu-20.04
    steps:

      - name: Get Token for checkout target organizatiom
        id: get_workflow_token_target
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APP_ID }}
          application_private_key: ${{ secrets.APP_SECRET }}
          organization: ${{ inputs.organization_name }}

      - name: Push repository changes
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token_target.outputs.token }}
          repository: ${{ inputs.repository_name }}-${{ inputs.user_name }}
        run: |
          gh repo delete ${{ inputs.organization_name }}/${{ env.repository }} --confirm