name: Demo Issue Form Opened

on:
  issues:
    types:
      - opened
      - reopened

# jobs:
#   parse_issue_labels:
#     if: |
#       contains(github.event.issue.labels.*.name, 'demo')
#       && contains(github.event.issue.labels.*.name, 'template')
#     uses: msanzdelrio-demo-resources/demo-workflows-bootstrap/.github/workflows/demo_create.yml@main
#     with:
#       user_name: ${{ github.event.issue.body.user.name }}
#       organization_name: ${{ github.event.issue.body.organization.value }}
#       repository_name: ${{ github.event.issue.body.repository }}

jobs:
  create_demo:
    runs-on: ubuntu-20.04
    steps:
      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'
      - run: |
          echo "${{ steps.parse.outputs.payload.user }}"