name: Demo Issue Form Opened

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  parse_issue_labels:
    if: |
      contains(github.event.issue.labels.*.name, 'demo')
      && contains(github.event.issue.labels.*.name, 'template')
    uses: msanzdelrio-demo-resources/demo-workflows-bootstrap/.github/workflows/demo_create.yml@main
    with:
      user_name: ${{ github.event.issue.body.user.name }}
      organization_name: ${{ github.event.issue.body.organization.value }}
      repository_name: ${{ github.event.issue.body.repository }}